#!/bin/bash

# args
PROJECT=$1	  # the project name: iamapi-server, northmarket-fix
GROUP=$2	  # the group under the project (the user group that use and manage the project) ie. wasabi, madev 
VERSION=$3	  # the version under the group
COMMAND=$4	  # the user command
COMMAND_ARG=$5    # the user arg command 
# vars
WAIT_TIME=5
ROOT_DIR=$APPS_HOME/$PROJECT
BIN_DIR=$APPS_HOME/bin
INSTALL_DIR=$ROOT_DIR/$GROUP/$VERSION
IMPLEM_VERSION=`cat $INSTALL_DIR/version.txt`					# look in this file the implem version
IMPLEM_VERSION_DIR=$INSTALL_DIR/version/$PROJECT-$IMPLEM_VERSION
PROCESS_NAME=`echo $GROUP|tr 'a-z' 'A-Z'`_`echo $PROJECT|tr 'a-z' 'A-Z'`_$VERSION		
CONF_DIR=$INSTALL_DIR/conf

#-----------------------------------------------------------------------------------
# functions 
#-----------------------------------------------------------------------------------

function die {
        echo "$@"
        exit 1
}

function startup {
        echo "starting $PROCESS_NAME" 
        cd $CONF_DIR || die "error cd $CONF_DIR"	 
        $BIN_DIR/start_process $IMPLEM_VERSION_DIR/$1 run $CONF_DIR $PROCESS_NAME > $INSTALL_DIR/$PROCESS_NAME.log &

	echo "waiting $WAIT_TIME seconds to let process start"
	sleep $WAIT_TIME
}

function shutdown {
	echo "stopping $PROCESS_NAME"
        cd $CONF_DIR || die "error cd $CONF_DIR"
        $BIN_DIR/kill_process $PROCESS_NAME
}

function checkStatus {
        cd $CONF_DIR || die "error cd $CONF_DIR"
        echo -n "status: " 
	$BIN_DIR/status_process $PROCESS_NAME
	echo "install dir: " $IMPLEM_VERSION_DIR
}

function showLog {
	less $IMPLEM_VERSION_DIR/$COMMAND_ARG
}

function showConsole {
        less $INSTALL_DIR/$PROCESS_NAME.log
}

function editConf {
	vim $CONF_DIR/$COMMAND_ARG
}

function clean {
	if [ -d  $IMPLEM_VERSION_DIR/$COMMAND_ARG ]; then
	        rm -r $IMPLEM_VERSION_DIR/$COMMAND_ARG
		echo  $IMPLEM_VERSION_DIR/$COMMAND_ARG "deleted"
	fi
}

function dump {
        cd $IMPLEM_VERSION_DIR || die "error cd $IMPLEM_VERSION_DIR"
	$IMPLEM_VERSION_DIR/admin $CONF_DIR $COMMAND $COMMAND_ARG 
}



#-----------------------------------------------------------------------------------
# main script
#-----------------------------------------------------------------------------------

# function choice
case $COMMAND in
        start)
                startup ${COMMAND_ARG:-run.xml}
                exit
        ;;

        status)
                checkStatus
                exit
        ;;

        stop)
                shutdown
                exit
        ;;

        restart)
                shutdown
                echo "Waiting 15 seconds"
                sleep 15
                startup ${COMMAND_ARG:-run.xml}
                exit
        ;;

	conf)
		editConf
		exit
	;;

	log)
		showLog
		exit
	;;

        console)
                showConsole
                exit
        ;;
  
	 clean)
                clean
                exit
        ;;

	dump)
                dump
                exit
        ;;

		
	*)
                echo -e "`basename $0` version $IMPLEM_VERSION\n"
                die "Usage: $0 {madev|wasabi} {version} {start|stop|restart|status|conf|log|console|clean|fix-start}" 
        ;;
esac
