#!/bin/bash

E_BADARGS=66
COLOR_RED='\E[31;40m'
COLOR_GREEN='\E[32;40m'
COLOR_YELLOW='\E[33;40m'
COLOR_BLUE='\E[34;40m'
COLOR_MAGENTA='\E[35;40m'
COLOR_CYAN='\E[36;40m'
COLOR_WHITE='\E[37;40m'

OS_SUN="SunOS"

if test -z "$1"  # No command line arg supplied?
then
  echo "Usage: $(basename $0) [Process_name]"
  exit $E_BADARGS
fi

PROCESS_NAME="$1"
OS=$(uname)

PS_CMD="ps"
if [ $OS == $OS_SUN ]
then
  PS_CMD="/usr/ucb/ps"
fi

if [ -f ./status_process ]
then
  PID=$(./status_process \-b $PROCESS_NAME)
else
  PID=$($PS_CMD axw | grep "\-Dprocess\.name=$PROCESS_NAME" | awk '{print $1}')
  NUMBER_OF_PID=$(echo "$PID" | wc -l | sed 's/^[ \t]*//;s/[ \t]*$//')
  if [ $NUMBER_OF_PID -gt 1 ]
  then
    PID=-1
  elif test -z $PID
  then
    PID=0
  fi
fi

if [ $PID == 0 ]
then
  echo "ERROR: No process named $PROCESS_NAME is running."
elif [ $PID == -1 ]
then
  echo -en "$COLOR_RED"
  echo "ERROR: process $PROCESS_NAME is running more than one time..."
  echo "       Execute 'status_process $PROCESS_NAME' to have more informations."
  tput sgr0
else
  $PS_CMD axw | grep "\-Dprocess\.name=$PROCESS_NAME" | awk '{print $1}' | xargs -i kill {} 2&>/dev/null
  echo "Process $PROCESS_NAME (PID=$PID) has been killed."
fi

exit $?
