#!/bin/bash

E_BADARGS=66
COLOR_RED='\E[31;40m'
COLOR_GREEN='\E[32;40m'
COLOR_YELLOW='\E[33;40m'
COLOR_BLUE='\E[34;40m'
COLOR_MAGENTA='\E[35;40m'
COLOR_CYAN='\E[36;40m'
COLOR_WHITE='\E[37;40m'

ECHO_MODE_BOOLEAN="BOOLEAN"
ECHO_MODE_NOT_BOOLEAN="NOT_BOOLEAN"
DEFAULT_ECHO_MODE=$ECHO_MODE_NOT_BOOLEAN

OS_SUN="SunOS"

if test -z "$1"  # No command line arg supplied?
then
  echo "Usage: $(basename $0) {Optional: -b|BOOLEAN} [Process_name}"
  exit $E_BADARGS
fi

ECHO_MODE=$DEFAULT_ECHO_MODE
if ! test -z "$2"
then
  ECHO_MODE=$1
  if [ $ECHO_MODE == '-b' ]
  then
    ECHO_MODE=$ECHO_MODE_BOOLEAN
  fi
fi

PROCESS_NAME=${2:-$1}
OS=$(uname)

PS_CMD="ps"
if [ $OS == $OS_SUN ]
then
  PS_CMD="/usr/ucb/ps"
fi

PID=$($PS_CMD axw | grep "\-Dprocess\.name=$PROCESS_NAME" | awk '{print $1}')
NUMBER_OF_PID=$(echo "$PID" | wc -l | sed 's/^[ \t]*//;s/[ \t]*$//')

if [ $NUMBER_OF_PID -gt 1 ]
then
  if [ $ECHO_MODE == $ECHO_MODE_BOOLEAN ]
  then
    echo -1
  else
    PIDS=$(echo $PID | sed '$!N;s/\n/ /')
    echo -en "Process $PROCESS_NAME is ["
    echo -en "$COLOR_MAGENTA"
    echo -en "Running $NUMBER_OF_PID Times: $PIDS"
    tput sgr0
    echo "]"
  fi

  exit $?
fi

if test -z $PID
then
  if [ $ECHO_MODE == $ECHO_MODE_BOOLEAN ]
  then
    echo 0
  else
    echo -en "Process $PROCESS_NAME is ["
    echo -en "$COLOR_RED"
    echo -en "Not Running"
    tput sgr0
    echo "]"
  fi
else
  if [ $ECHO_MODE == $ECHO_MODE_BOOLEAN ]
  then
    echo $PID
  else
    #NUMBER_OF_PID=$(echo "$PID" | wc -l)
    #echo $NUMBER_OF_PID
    echo -en "Process $PROCESS_NAME is ["
    echo -en "$COLOR_GREEN"
    echo -en "Running With PID $PID"
    tput sgr0
    echo "]"
  fi
fi

exit $?