#! /bin/bash
# =============================================================================
# regenerate .ssh/autorized_keys from gitosis
# =============================================================================

authorized_keys_path=".ssh/authorized_keys"
authorized_keys_backup=$authorized_keys_path.$(date +%Y%m%d_%H%M%S)

gitosis_keys_dir=/data/gitosis/repositories/gitosis-admin.git/gitosis-export/keydir

echo "================================================================================="
echo "build $authorized_keys_path from gitosis keys: $gitosis_keys_dir"
echo "================================================================================="

echo
echo "save $authorized_keys_path to $authorized_keys_backup"
mv $authorized_keys_path $authorized_keys_backup

echo "# =================================================================================" >> $authorized_keys_path
echo "# autogenerated by $0 - DO NOT EDIT" >>  $authorized_keys_path
echo "# =================================================================================" >> $authorized_keys_path

for key_file in $gitosis_keys_dir/*.pub
do
        echo "add key $key_file"
        cat $key_file >> $authorized_keys_path
        echo "" >> $authorized_keys_path
done

echo "file built successfully"

